secrets:
    sops:
        age_key: ENC[AES256_GCM,data:cGc4zvFKdlH/yjXhvVzZ73kjG7dMpokVtsZrHlCkShSUHXwQ/p7XyQqvCCM5wfJuRaJphQEQZplJA4DP1xbon4n1qXdEhFzYThK4,iv:/OF3r324u2dFTDmzyRC4jQS18iDRM3DuvxI9ftMYbcg=,tag:h+tndsYD0A8TkiPivnI9Gg==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:Sr3cpek4SyCyjag/I6Rq9Cu6E+h6TwaLKA==,iv:eE7OcNwrzx3CKBK1CeLaHLoUAT7gzlfvro1SbYl6Qvw=,tag:Q3mEFeziBQZI7MezlZQG9g==,type:str]
            username: ENC[AES256_GCM,data:6k18BluX6gDjp0jRC/wZ1gITqdfYuaZE3g==,iv:CacFh16P0FsqYFwqaNx0x9tJlDNnXRI/62ym5/o5l6A=,tag:ped+RBaV32wL9OJ+d5CB+w==,type:str]
            password: ENC[AES256_GCM,data:gGp8SGEOlnxVO7OyezI=,iv:naowT+su5YpI9emck18AWGRbKcBF58amLwc/JqxMWhE=,tag:rduPvDril81OvKF/eDARJg==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:xFCHQGLslc6egoQ=,iv:60RhPRbq3PwliSgXFq4a4YIiXRyNULeZWZU+q/O8APU=,tag:o0i8VYI7EHnAqCicS2DrGQ==,type:str]
                password: ENC[AES256_GCM,data:qzVnuKv8EppH+pAkuo5Eqcghuo6nF5NfkUdjjY6Ndwl+Rx3Hp/LzIA==,iv:dLzNTkEfQlUsxE1B1TD/7lqmJMzROzaPckqsVg0Vjso=,tag:g+63S7/kyk1Odo6KSKn/5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY3oyd09EM3VqYmcyTEZa
            YnlhWTc3UjRwdnNiK1hxcmJNVzdrcXB2NHo4ClpMdU1MdytvanIyZ3J5REhOZmov
            VWprMWo0VVRiRzNYVFk2OTVpTzJrekEKLS0tIG9oSTBQcThkV0JnSzlLRjJ1YzRu
            YVUxZk92bmxXckRXNVBzR0E1bmpMclUKnRSiME0F6o5y98JWGrLoTXxuaU0hTSTF
            cYUydASu1e/J20ktFSDBMbj+0dhrlLWkC8Tkws/Rll6TLj1KYuJGRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T07:20:28Z"
    mac: ENC[AES256_GCM,data:Rqh+4TeWxD3XEznIh0TxVSKOsz01DhXV9Wfjf2NFj6VsvqhYFe4cKIzACT68Opuus7wUVfsnOsrQhTluwbsItjhVJRJmAAG0Qa1gMDTONlXzctowBikJ9Gm3/D6j3D3jKayQe/kD+pa/hvKnKvOQBUq7Lvt4nSRxUckF70fL79k=,iv:UNFxQV7bqqgbm+ffbvcAtipCN8jtcCvwru8hEY53cb4=,tag:3Yh4hJoagiOIw2nO/Lh5Wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
