tap_install:
    sensitive_values:
        shared:
            ingress_domain: ENC[AES256_GCM,data:D/SQgVR0ctODJPmsumI3PhG2dyOoQ7kwWF1pG1exeJhxY7nS9PGC7U6KOC0=,iv:Z5WpYSOGEpD0jgFaR8kjNOvL1eEw6oXtjApwmIdIFT0=,tag:M6hg8GMPo/uTob68F9crJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodmxhOW05TlZrRkoydFZK
            TlBJaWQ0TlN1blNQNFN6YWV5REhIUU5uOWlZCmZJNmtqVUVLVHFqQWllRGdyRklk
            YTJJZUxldW00amFoQkdUWWs0OWtWTE0KLS0tIEg3SFZ2SjdLTlo2ai9NVDltL0tE
            NXp4MFM5d09qQks2eEVSaHBJcEo0K1kKXxCkwMjotIwW8ELVuPCtPybrZFrSM5wD
            hkQT97hw5YQtt0tepoAfN+l3EsBjucXhoErMXvmQokZ60eQvkXOAQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T07:20:28Z"
    mac: ENC[AES256_GCM,data:FxI++7z3AWnbWre73WO/WsfLVakYRV11yze5HCWT9gpzb+gEnr7wHxLN3bMwBC58YJaQaWGwJOHuMTeVjSHgnCAd+iJUG3kdB2YM32tOEMF556PLppOHGEOw2NK/hg3S7tEFlDyUoTeeNkuowbambcn2NhWllwXhHfCIfNRV/yA=,iv:Q4eCIyHE+X7uBAWNEu7hbEQNbT0QUM4P/SZaKSCf3Ew=,tag:BDnyKKg1i9sKG2K26juwzQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
